# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sequence.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import note_type_pb2 as note__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esequence.proto\x1a\x0fnote_type.proto\"a\n\x04Note\x12\x17\n\x04type\x18\x01 \x01(\x0e\x32\t.NoteType\x12\x0c\n\x04time\x18\x02 \x01(\x02\x12\x0e\n\x06length\x18\x03 \x01(\x02\x12\x12\n\ninstrument\x18\x04 \x01(\x05\x12\x0e\n\x06volume\x18\x05 \x01(\x02\"Y\n\x06Marker\x12\x0c\n\x04time\x18\x01 \x01(\x02\x12\x0f\n\x07setting\x18\x02 \x01(\x05\x12\x12\n\ninstrument\x18\x03 \x01(\x05\x12\r\n\x05value\x18\x04 \x01(\x02\x12\r\n\x05\x62lend\x18\x05 \x01(\x08\"\x88\x02\n\x12InstrumentSettings\x12\x0e\n\x06volume\x18\x01 \x01(\x02\x12\r\n\x05\x64\x65lay\x18\x02 \x01(\x08\x12\x0e\n\x06reverb\x18\x03 \x01(\x08\x12\x13\n\x0breverb_type\x18\n \x01(\x05\x12\x1f\n\x17one_minus_reverb_volume\x18\x0b \x01(\x02\x12\x0b\n\x03pan\x18\x04 \x01(\x02\x12\x11\n\tenable_eq\x18\x05 \x01(\x08\x12\x0e\n\x06\x65q_low\x18\x06 \x01(\x02\x12\x0e\n\x06\x65q_mid\x18\x07 \x01(\x02\x12\x0f\n\x07\x65q_high\x18\x08 \x01(\x02\x12\x0e\n\x06\x64\x65tune\x18\t \x01(\x02\x12\x14\n\x0c\x64istort_type\x18\x0c \x01(\x05\x12\x16\n\x0e\x64istort_volume\x18\r \x01(\x02\"\xd3\x01\n\x10SequenceSettings\x12\x0b\n\x03\x62pm\x18\x01 \x01(\x05\x12\x16\n\x0etime_signature\x18\x02 \x01(\x05\x12\x37\n\x0binstruments\x18\x03 \x03(\x0b\x32\".SequenceSettings.InstrumentsEntry\x12\x18\n\x10one_minus_volume\x18\x04 \x01(\x02\x1aG\n\x10InstrumentsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.InstrumentSettings:\x02\x38\x01\"_\n\x08Sequence\x12#\n\x08settings\x18\x01 \x01(\x0b\x32\x11.SequenceSettings\x12\x14\n\x05notes\x18\x02 \x03(\x0b\x32\x05.Note\x12\x18\n\x07markers\x18\x03 \x03(\x0b\x32\x07.Markerb\x06proto3')



_NOTE = DESCRIPTOR.message_types_by_name['Note']
_MARKER = DESCRIPTOR.message_types_by_name['Marker']
_INSTRUMENTSETTINGS = DESCRIPTOR.message_types_by_name['InstrumentSettings']
_SEQUENCESETTINGS = DESCRIPTOR.message_types_by_name['SequenceSettings']
_SEQUENCESETTINGS_INSTRUMENTSENTRY = _SEQUENCESETTINGS.nested_types_by_name['InstrumentsEntry']
_SEQUENCE = DESCRIPTOR.message_types_by_name['Sequence']
Note = _reflection.GeneratedProtocolMessageType('Note', (_message.Message,), {
  'DESCRIPTOR' : _NOTE,
  '__module__' : 'sequence_pb2'
  # @@protoc_insertion_point(class_scope:Note)
  })
_sym_db.RegisterMessage(Note)

Marker = _reflection.GeneratedProtocolMessageType('Marker', (_message.Message,), {
  'DESCRIPTOR' : _MARKER,
  '__module__' : 'sequence_pb2'
  # @@protoc_insertion_point(class_scope:Marker)
  })
_sym_db.RegisterMessage(Marker)

InstrumentSettings = _reflection.GeneratedProtocolMessageType('InstrumentSettings', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUMENTSETTINGS,
  '__module__' : 'sequence_pb2'
  # @@protoc_insertion_point(class_scope:InstrumentSettings)
  })
_sym_db.RegisterMessage(InstrumentSettings)

SequenceSettings = _reflection.GeneratedProtocolMessageType('SequenceSettings', (_message.Message,), {

  'InstrumentsEntry' : _reflection.GeneratedProtocolMessageType('InstrumentsEntry', (_message.Message,), {
    'DESCRIPTOR' : _SEQUENCESETTINGS_INSTRUMENTSENTRY,
    '__module__' : 'sequence_pb2'
    # @@protoc_insertion_point(class_scope:SequenceSettings.InstrumentsEntry)
    })
  ,
  'DESCRIPTOR' : _SEQUENCESETTINGS,
  '__module__' : 'sequence_pb2'
  # @@protoc_insertion_point(class_scope:SequenceSettings)
  })
_sym_db.RegisterMessage(SequenceSettings)
_sym_db.RegisterMessage(SequenceSettings.InstrumentsEntry)

Sequence = _reflection.GeneratedProtocolMessageType('Sequence', (_message.Message,), {
  'DESCRIPTOR' : _SEQUENCE,
  '__module__' : 'sequence_pb2'
  # @@protoc_insertion_point(class_scope:Sequence)
  })
_sym_db.RegisterMessage(Sequence)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEQUENCESETTINGS_INSTRUMENTSENTRY._options = None
  _SEQUENCESETTINGS_INSTRUMENTSENTRY._serialized_options = b'8\001'
  _NOTE._serialized_start=35
  _NOTE._serialized_end=132
  _MARKER._serialized_start=134
  _MARKER._serialized_end=223
  _INSTRUMENTSETTINGS._serialized_start=226
  _INSTRUMENTSETTINGS._serialized_end=490
  _SEQUENCESETTINGS._serialized_start=493
  _SEQUENCESETTINGS._serialized_end=704
  _SEQUENCESETTINGS_INSTRUMENTSENTRY._serialized_start=633
  _SEQUENCESETTINGS_INSTRUMENTSENTRY._serialized_end=704
  _SEQUENCE._serialized_start=706
  _SEQUENCE._serialized_end=801
# @@protoc_insertion_point(module_scope)
